# Site settings
title: Patrick McFadin
description: Computer Engineer & Technologist | Distributed Computing Expert | Open Source Advocate
author: Patrick McFadin
email: 
baseurl: ""
url: "https://pmcfadin.github.com"

# Social links
social:
  twitter: PatrickMcFadin
  github: pmcfadin
  linkedin: patrick-mcfadin-53a8046

# Build settings
markdown: kramdown
theme: 
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  articles:
    output: true
    permalink: /articles/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CLAUDE.md
  - .gitignore
  - vendor/